def decrypt(text=''):
    '''
    Description:
    This function is used to decrypt texts generated by the encrypt function in the crypto module.

    Parameters:
    - text (str): The only parameter to be entered is the text you want to decrypt.

    Returns:
    (str): This function only returns the decrypted text.
    '''
    text = input('\033[36mEnter the text to be decrypted: \033[m')  # Input of the (encrypted) text.
    list1 = []
    list2 = []
    list3 = []

    # Splitting the text into two, in order to handle each part separately.
    truncat_e = len(text) // 2
    for truncat_1 in text[truncat_e:]:  # Second half.
        list1.append(truncat_1)

    for truncat_2 in text[:truncat_e]:  # First half.
        list2.append(truncat_2)

    # Handling the second half with the reverse logic of encryption.
    for char_2 in list1:
        char_2 = ord(char_2) + 2
        char_2 = chr(char_2)
        list3.append(char_2)  # Second half treated.
    list1.clear()

    # Joining the two halves.
    for letter2 in list2:
        list1.append(letter2)  # Adding the first half.
    list2.clear()

    for letter3 in list3:
        list1.append(letter3)  # Adding the second half (1st treatment).
    list3.clear()

    # Reversing list1.
    for letter in list1[::-1]:
        list2.append(letter)
    list1.clear()

    # list2 now has all characters and is reversed.
    # Adding the second treatment to the text.
    for char_1 in list2:
        
        char_1 = ord(char_1) - 5
        char_1 = chr(char_1)
        list1.append(char_1)
        

    # Printing what has been fully treated.
    for line_ in list1:
        print(f'\033[32m{line_}\033[m', end='')
